build:
  - &build-setting
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
      tags: [ "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}", "${DRONE_TAG:-latest}" ]
    repo: registry.eyeteam.vn/bitex/bitex-dashboard
    registry: registry.eyeteam.vn
    dockerfile: Dockerfile
    use_cache: true
    purge: false

  - &docker-build
    name: docker-build
    image: plugins/docker
    settings:
      <<: *build-setting
    volumes:
    - name: docker
      path: /var/lib/docker

kind: pipeline
type: docker
name: build

concurrency:
  limit: 1

steps:
- name: prepare
  image: busybox
  commands:
    - mkdir -p /docker/${DRONE_REPO}/docker
    - sh prepare.sh package.json
    - sh prepare.sh package-lock.json
  volumes:
    - name: cache
      path: /cache

- <<: *docker-build
  name: staging
  settings:
    <<: *build-setting
    tags: ["stg-${DRONE_TAG}"]
    build_args:
    - MODE=stg
  when:
    ref:
    - refs/tags/*

- <<: *docker-build
  name: production
  settings:
    <<: *build-setting
    tags: ["${DRONE_TAG}"]
    build_args:
    - MODE=prod
  when:
    ref:
    - refs/tags/*.0

- name: telegram
  image: appleboy/drone-telegram
  settings:
    token: 156097778:AAGUkHpuAY-RihvCVHA7g_E1vHfEnb45pF4
    to: "-324611566"
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{/success}}
  when:
    status: [ failure ]

volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: docker
    host:
      path: /tmp/cache/${DRONE_REPO}/docker

trigger:
  event:
  - tag
  # branch:
  # - ci

---

kind: pipeline
type: docker
name: deploy

clone:
  disable: true

steps:
- name: deploy-staging
  image: appleboy/drone-ssh:1.5.5
  settings:
    host: bitex.eyeteam.vn
    username: app
    password:
      from_secret: ssh_password
    port: 22
    script:
      - export IMAGE_TAG="stg-${DRONE_TAG}"
      - DOCKER_REPO='registry.eyeteam.vn/bitex/bitex-dashboard'
      - export DOCKER_DASHBOARD_IMAGE=$DOCKER_REPO:$IMAGE_TAG
      - docker pull $DOCKER_DASHBOARD_IMAGE
      - cd ./bitex/deployment
      - docker-compose -p bitex stop dashboard
      - docker-compose -p bitex rm -f dashboard
      - docker-compose -p bitex up -d dashboard
  when:
    ref:
    - refs/tags/*

- name: deploy-prod
  image: appleboy/drone-ssh:1.5.5
  settings:
    host: dashboard.bitexshop.com
    username: ubuntu
    password:
      from_secret: ssh_prod_password
    port: 22
    script:
      - export IMAGE_TAG="${DRONE_TAG}"
      - DOCKER_REPO='registry.eyeteam.vn/bitex/bitex-dashboard'
      - export DOCKER_API_IMAGE=$DOCKER_REPO:$IMAGE_TAG
      - docker pull $DOCKER_API_IMAGE
      - cd ./deployment
      - docker-compose -p bitex stop dashboard
      - docker-compose -p bitex rm -f dashboard
      - docker-compose -p bitex up -d dashboard
  when:
    ref:
    - refs/tags/*.0

- name: telegram
  image: appleboy/drone-telegram
  settings:
    token: 156097778:AAGUkHpuAY-RihvCVHA7g_E1vHfEnb45pF4
    to: "-324611566"
    message: >
      {{#success build.status}}
      ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{else}}
      ❌ Build #{{build.number}} of `{{repo.name}}` failed.
      📝 Commit by {{commit.author}} on `{{commit.branch}}`:
      ```
      {{commit.message}}
      ```
      🌐 {{ build.link }}
      {{/success}}
  when:
    status: [ success, failure ]

depends_on:
  - build

trigger:
  event:
  - tag

---
kind: secret
name: docker_username
get:
  path: secret/docker
  name: username

---
kind: secret
name: docker_password
get:
  path: secret/docker
  name: password

---
kind: secret
name: ssh_password
get:
  path: secret/ssh_deploy
  name: app_eyeteam

---
kind: secret
name: ssh_prod_password
get:
  path: secret/ssh_prod_deploy
  name: ubuntu_bitex
