export const SIDEBAR_INIT = "SIDEBAR_INIT";
export const INIT_LANGUAGES = "INIT_LANGUAGES";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

// users
export const AUTH_REQUEST = "AUTH_REQUEST";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";

// articles
export const FETCH_ARTICLES = "FETCH_ARTICLES";
export const FETCH_ARTICLE_DETAIL = "FETCH_ARTICLE_DETAIL";

// product
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const STORE_PRODUCT = "STORE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

// categories
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY_DETAIL = "FETCH_CATEGORY_DETAIL";
export const UPDATE_CATEGORY_DETAIL = "UPDATE_CATEGORY_DETAIL";

// attributes
export const FETCH_ATTRIBUTES = "FETCH_ATTRIBUTES";
export const FETCH_ATTRIBUTE_DETAIL = "FETCH_ATTRIBUTE_DETAIL";
export const UPDATE_ATTRIBUTE_DETAIL = "UPDATE_ATTRIBUTE_DETAIL";
export const CREATE_ATTRIBUTE = "CREATE_ATTRIBUTE";
export const CREATE_ATTRIBUTE_OPTION = "CREATE_ATTRIBUTE_OPTION";
export const UPDATE_ATTRIBUTE_OPTION = "UPDATE_ATTRIBUTE_OPTION";

// review
export const FETCH_REVIEWS = "FETCH_REVIEWS";
export const FETCH_REVIEW_DETAIL = "FETCH_REVIEW_DETAIL";
export const FETCH_REVIEW_REPLIES = "FETCH_REVIEW_REPLIES";

// notification
export const FETCH_NOTIFICATIONS = "FETCH_NOTIFICATIONS";
export const FETCH_NOTIFICATION_DETAIL = "FETCH_NOTIFICATION_DETAIL";

// variant
export const STORE_VARIANT = "STORE_VARIANT";

// permissions
export const FETCH_PERMISSIONS = "FETCH_PERMISSIONS";
export const FETCH_ROLE_DETAIL = "FETCH_ROLE_DETAIL";

// attribute
export const FETCH_PRODUCT_ATTRIBUTES = "FETCH_PRODUCT_ATTRIBUTES";
export const FETCH_VARIANT_ATTRIBUTES = "FETCH_VARIANT_ATTRIBUTES";
export const FETCH_COLOR_ATTRIBUTES = "FETCH_COLOR_ATTRIBUTES";

// collection
export const FETCH_COLLECTIONS = "FETCH_COLLECTIONS";
export const FETCH_COLLECTION_DETAIL = "FETCH_COLLECTION_DETAIL";
export const STORE_COLLECTION = "STORE_COLLECTION";
export const UPDATE_COLLECTION = "UPDATE_COLLECTION";
export const REMOVE_COLLECTION = "REMOVE_COLLECTION";
export const REMOVE_PRODUCT_COLLECTION = "REMOVE_PRODUCT_COLLECTION";

// order
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDER_DETAIL = "FETCH_ORDER_DETAIL";
export const STORE_ORDER = "STORE_ORDER";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const FETCH_ORDER_SHIPPING = "FETCH_ORDER_SHIPPING";

export const FETCH_CUSTOMER = "FETCH_CUSTOMER";

export const FETCH_TESTIMONIAL = "FETCH_TESTIMONIAL";
export const FETCH_TESTIMONIAL_DETAIL = "FETCH_TESTIMONIAL_DETAIL";
export const REMOVE_TESTIMONIAL = "REMOVE_TESTIMONIAL";

export const FETCH_CLIENT = "FETCH_CLIENT";
export const FETCH_CLIENT_DETAIL = "FETCH_CLIENT_DETAIL";
export const REMOVE_CLIENT = "REMOVE_CLIENT";

export const FETCH_SUBSCRIBER = "FETCH_SUBSCRIBER";
export const FETCH_CONTACT = "FETCH_CONTACT";
export const FETCH_CONTACT_DETAIL = "FETCH_CONTACT_DETAIL";
export const FETCH_REVIEW = "FETCH_REVIEW";
export const FETCH_COMMENT = "FETCH_COMMENT";
// pape
export const FETCH_PAGES = "FETCH_PAGES";
export const FETCH_PAGE_DETAIL = "FETCH_PAGE_DETAIL";
export const STORE_PAGE = "STORE_PAGE";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const REMOVE_PAGE = "REMOVE_PAGE";
// coupon
export const FETCH_COUPONS = "FETCH_COUPONS";
export const FETCH_COUPON_DETAIL = "FETCH_COUPON_DETAIL";
export const STORE_COUPON = "STORE_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const REMOVE_COUPON = "REMOVE_COUPON";

// CAMPAIGN
export const FETCH_CAMPAIGNS = "FETCH_CAMPAIGNS";
export const FETCH_CAMPAIGN_DETAIL = "FETCH_CAMPAIGN_DETAIL";
export const STORE_CAMPAIGN = "STORE_CAMPAIGN";
export const REMOVE_CAMPAIGN = "REMOVE_CAMPAIGN";

// FLASHSALE
export const FETCH_FLASHSALES = "FETCH_FLASHSALES";
export const FETCH_FLASHSALE_DETAIL = "FETCH_FLASHSALE_DETAIL";
export const STORE_FLASHSALE = "STORE_FLASHSALE";
export const REMOVE_FLASHSALE = "REMOVE_FLASHSALE";
export const FETCH_PROVINCES = "FETCH_PROVINCES";

// DISTRICT, WARD
export const FETCH_DISTRICTS = "FETCH_DISTRICTS";
export const FETCH_WARDS = "FETCH_WARDS";

// menu
export const FETCH_MENUS = "FETCH_MENUS";
export const FETCH_MENU_DETAIL = "FETCH_MENU_DETAIL";
export const FETCH_MENU_DETAIL_EDIT = "FETCH_MENU_DETAIL_EDIT";
export const UPDATE_MENU = "UPDATE_MENU";
export const REMOVE_MENU = "REMOVE_MENU";
export const FETCH_TAGS = "FETCH_TAGS";

// META
export const FETCH_META = "FETCH_META";
export const FETCH_PALETTE = "FETCH_PALETTE";
export const FETCH_COUPON_SETTING_META = "FETCH_COUPON_SETTING_META";
export const STORE_META = "STORE_META";
export const UPDATE_META = "UPDATE_META";
export const REMOVE_META = "REMOVE_META";

// user
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER_DETAIL = "FETCH_USER_DETAIL";
export const STORE_USER = "STORE_USER";
export const REMOVE_USER = "REMOVE_USER";

// roles
export const FETCH_ROLE = "FETCH_ROLE";
export const FETCH_HISTORY = "FETCH_HISTORY";
export const FETCH_SHIPPING = "FETCH_SHIPPING";
export const FETCH_SHIPPING_DETAIL = "FETCH_SHIPPING_DETAIL";
export const FETCH_SHIPPING_EDIT = "FETCH_SHIPPING_EDIT";

export const FETCH_DELETED = "FETCH_DELETED";
export const FETCH_DELETED_DETAIL = "FETCH_DELETED_DETAIL";
export const MESSAGE = "MESSAGE";
export const SET_CURRENT_ACTIONS = "SET_CURRENT_ACTIONS";
export const SET_PAGE_TITLE = "SET_PAGE_TITLE";

export const FETCH_DASHBOARD_STATISTIC = "FETCH_DASHBOARD_STATISTIC";

export const FETCH_CUSTOMER_DETAIL = "FETCH_CUSTOMER_DETAIL";
export const FETCH_CUSTOMER_ORDERS = "FETCH_CUSTOMER_ORDERS";

// MODEL
export const FETCH_MODEL = "FETCH_MODEL";
export const STORE_MODEL = "STORE_MODEL";
export const UPDATE_MODEL = "UPDATE_MODEL";
export const REMOVE_MODEL = "REMOVE_MODEL";

// PRODUCT ERROR
export const FETCH_PRODUCT_ERROR = "FETCH_PRODUCT_ERROR";
export const STORE_PRODUCT_ERROR = "STORE_PRODUCT_ERROR";
export const UPDATE_PRODUCT_ERROR = "UPDATE_PRODUCT_ERROR";
export const REMOVE_PRODUCT_ERROR = "REMOVE_PRODUCT_ERROR";

// PRODUCT Accessories
export const FETCH_PRODUCT_ACCESSORIES = "FETCH_PRODUCT_ACCESSORIES";
export const STORE_PRODUCT_ACCESSORIES = "STORE_PRODUCT_ACCESSORIES";
export const UPDATE_PRODUCT_ACCESSORIES = "UPDATE_PRODUCT_ACCESSORIES";
export const REMOVE_PRODUCT_ACCESSORIES = "REMOVE_PRODUCT_ACCESSORIES";

// WARRANTY CODE
export const FETCH_WARRANTY_CODE = "FETCH_WARRANTY_CODE";
export const STORE_WARRANTY_CODE = "STORE_WARRANTY_CODE";
export const REMOVE_WARRANTY_CODE = "REMOVE_WARRANTY_CODE";

// WARRANTY FORM
export const FETCH_WARRANTY_FORMS = "FETCH_WARRANTY_FORMS";
export const STORE_WARRANTY_FORM = "STORE_WARRANTY_FORM";
export const REMOVE_WARRANTY_FORM = "REMOVE_WARRANTY_FORM";
export const FETCH_WARRANTY_FORM_DETAIL = "FETCH_WARRANTY_FORM_DETAIL";
export const CONTACT_WARRANTY_FORM = "CONTACT_WARRANTY_FORM";

// WARRANTY LOCATION
export const FETCH_WARRANTY_LOCATIONS = "FETCH_WARRANTY_LOCATIONS";
export const FETCH_WARRANTY_LOCATION_DETAIL = "FETCH_WARRANTY_LOCATION_DETAIL";
export const CREATE_WARRANTY_LOCATION = "CREATE_WARRANTY_LOCATION";
export const UPDATE_WARRANTY_LOCATION = "UPDATE_WARRANTY_LOCATION";
export const REMOVE_WARRANTY_LOCATION = "REMOVE_WARRANTY_LOCATION";

// Receipt
export const FETCH_RECEIPTS = "FETCH_RECEIPTS";
export const STORE_RECEIPT = "STORE_RECEIPT";
export const REMOVE_RECEIPT = "REMOVE_RECEIPT";
export const FETCH_RECEIPT_DETAIL = "FETCH_RECEIPT_DETAIL";

// quotation
export const FETCH_QUOTATIONS = "FETCH_QUOTATIONS";
export const STORE_QUOTATION = "STORE_QUOTATION";
export const REMOVE_QUOTATION = "REMOVE_QUOTATION";
export const FETCH_QUOTATION_DETAIL = "FETCH_QUOTATION_DETAIL";

// bill
export const FETCH_INVOICES = "FETCH_INVOICES";
export const STORE_INVOICE = "STORE_INVOICE";
export const REMOVE_INVOICE = "REMOVE_INVOICE";
export const FETCH_INVOICE_DETAIL = "FETCH_INVOICE_DETAIL";

// reimbursement
export const FETCH_REIMBURSEMENTS = "FETCH_REIMBURSEMENTS";
export const STORE_REIMBURSEMENT = "STORE_REIMBURSEMENT";
export const REMOVE_REIMBURSEMENT = "REMOVE_REIMBURSEMENT";
export const FETCH_REIMBURSEMENT_DETAIL = "FETCH_REIMBURSEMENT_DETAIL";
// test result
export const FETCH_MAINTENANCE_FORMS = "FETCH_MAINTENANCE_FORMS";
export const STORE_MAINTENANCE_FORM = "STORE_MAINTENANCE_FORM";
export const REMOVE_MAINTENANCE_FORM = "REMOVE_MAINTENANCE_FORM";
export const FETCH_MAINTENANCE_FORM_DETAIL = "FETCH_MAINTENANCE_FORM_DETAIL";

// warranty post
export const FETCH_WARRANTY_POSTS = "FETCH_WARRANTY_POSTS";
export const STORE_WARRANTY_POST = "STORE_WARRANTY_POST";
export const REMOVE_WARRANTY_POST = "REMOVE_WARRANTY_POST";
export const FETCH_WARRANTY_POST_DETAIL = "FETCH_WARRANTY_POST_DETAIL";
export const UPDATE_WARRANTY_POST = "UPDATE_WARRANTY_POST";
export const CREATE_WARRANTY_POST = "CREATE_WARRANTY_POST";

// education post
export const FETCH_EDUCATION_POSTS = "FETCH_EDUCATION_POSTS";
export const STORE_EDUCATION_POST = "STORE_EDUCATION_POST";
export const REMOVE_EDUCATION_POST = "REMOVE_EDUCATION_POST";
export const FETCH_EDUCATION_POST_DETAIL = "FETCH_EDUCATION_POST_DETAIL";

// add CREATE_EDUCATION for testing
export const CREATE_EDUCATION_POST = "CREATE_EDUCATION_POST";
export const UPDATE_EDUCATION_POST = "UPDATE_EDUCATION_POST";

// education coupon
export const FETCH_EDUCATION_COUPONS = "FETCH_EDUCATION_COUPONS";
export const FETCH_EDUCATION_COUPON_DETAIL = "FETCH_EDUCATION_COUPON_DETAIL";
export const CREATE_EDUCATION_COUPON = "CREATE_EDUCATION_COUPON";
export const UPDATE_EDUCATION_COUPON = "UPDATE_EDUCATION_COUPON";
export const REMOVE_EDUCATION_COUPON = "REMOVE_EDUCATION_COUPON ";

// volume
export const FETCH_VOLUMES = "FETCH_VOLUMES";
export const UPDATE_VOLUME = "UPDATE_VOLUME";
export const STORE_VOLUME = "STORE_VOLUME";
export const REMOVE_VOLUME = "REMOVE_VOLUME";
export const FETCH_VOLUME_DETAIL = "FETCH_VOLUME_DETAIL";
// document
export const FETCH_DOCUMENTS = "FETCH_DOCUMENTS";
export const FETCH_DOCUMENT_DETAIL = "FETCH_DOCUMENT_DETAIL";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const REMOVE_DOCUMENT = "REMOVE_DOCUMENT";
// teacher
export const FETCH_TEACHERS = "FETCH_TEACHERS";
export const FETCH_TEACHER_DETAIL = "FETCH_TEACHER_DETAIL";
export const UPDATE_TEACHER = "UPDATE_TEACHER";
export const REJECT_TEACHER = "REJECT_TEACHER";
export const CONFIRM_TEACHER = "CONFIRM_TEACHER";
// survey
export const FETCH_SURVEYS = "FETCH_SURVEYS";
export const FETCH_SURVEY_DETAIL = "FETCH_SURVEY_DETAIL";
export const CREATE_SURVEY = "CREATE_SURVEY";
export const UPDATE_SURVEY = "UPDATE_SURVEY";
export const REMOVE_SURVEY = "DELETE_SURVEY";
// survey question
export const FETCH_SURVEY_QUESTIONS = "FETCH_SURVEY_QUESTIONS";
export const FETCH_SURVEY_QUESTION_DETAIL = "FETCH_SURVEY_QUESTION_DETAIL";
export const CREATE_SURVEY_QUESTION = "CREATE_SURVEY_QUESTION";
export const UPDATE_SURVEY_QUESTION = "UPDATE_SURVEY_QUESTION";
export const REMOVE_SURVEY_QUESTION = "REMOVE_SURVEY_QUESTION";

// exam
export const FETCH_EXAMS = "FETCH_EXAMS";
export const FETCH_EXAM_DETAIL = "FETCH_EXAM_DETAIL";
export const CREATE_EXAM = "CREATE_EXAM";
export const UPDATE_EXAM = "UPDATE_EXAM";
export const REMOVE_EXAM = "DELETE_EXAM";
// question
export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const FETCH_QUESTION_DETAIL = "FETCH_QUESTION_DETAIL";
export const CREATE_QUESTION = "CREATE_QUESTION";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const REMOVE_QUESTION = "REMOVE_QUESTION";
// answer
export const FETCH_ANSWERS = "FETCH_ANSWERS";
export const FETCH_ANSWER_DETAIL = "FETCH_ANSWER_DETAIL";
export const CREATE_ANSWER = "CREATE_ANSWER";
export const UPDATE_ANSWER = "UPDATE_ANSWER";
export const DELETE_ANSWER = "DELETE_ANSWER";
// ticket
export const FETCH_TICKETS = "FETCH_TICKETS";
export const CLOSE_TICKET = "CLOSE_TICKET";
export const CLEAR_TICKETS = "CLEAR_TICKETS";
export const FETCH_REPORT = "FETCH_REPORT";

// customer service coupon
export const FETCH_CS_COUPONS = "FETCH_CS_COUPONS";
export const FETCH_CS_COUPON_DETAIL = "FETCH_CS_COUPON_DETAIL";
export const CREATE_CS_COUPON = "CREATE_CS_COUPON";
export const UPDATE_CS_COUPON = "UPDATE_CS_COUPON";
export const REMOVE_CS_COUPON = "REMOVE_CS_COUPON ";

// activated products
export const FETCH_ACTIVATED_PRODUCTS = "FETCH_ACTIVATED_PRODUCTS";

export const FETCH_SETTING_DATA = "FETCH_SETTING_DATA";

export const FETCH_MY_ROOMS = "FETCH_MY_ROOMS";

export const CREATE_ROOM = "CREATE_ROOM";

export const FETCH_ROOM_DETAIL = "FETCH_ROOM_DETAIL";

export const REMOVE_ROOM = "REMOVE_ROOM";

export const FETCH_DEPARTMENTS = "FETCH_DEPARTMENTS";

export const CREATE_DEPARTMENT = "CREATE_DEPARTMENT";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";

export const REMOVE_DEPARTMENT = "REMOVE_DEPARTMENT";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

export const FETCH_COURSES = "FETCH_COURSES";

export const CREATE_COURSE = "CREATE_COURSE";

export const FETCH_COURSE = "FETCH_COURSE";

export const REMOVE_COURSE = "REMOVE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const FETCH_ROOM_STUDENTS = "FETCH_ROOM_STUDENTS";
export const RESET_ROOM_STUDENTS = "RESET_ROOM_STUDENTS";

export const FETCH_GROUPS = "FETCH_GROUPS";

export const CREATE_GROUP = "CREATE_GROUP";

export const FETCH_GROUP = "FETCH_GROUP";

export const FETCH_ROOMS_GROUP_BY_ID = "FETCH_ROOMS_GROUP_BY_ID";

export const FETCH_GROUP_STATISTIC = "FETCH_GROUP_STATISTIC";

export const FETCH_GROUP_STUDENT = "FETCH_GROUP_STUDENT";

export const ADD_GROUP_STUDENTS = "ADD_GROUP_STUDENTS";

export const RESET_GROUP_STUDENTS = "RESET_GROUP_STUDENTS";

export const REMOVE_GROUP = "REMOVE_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";

export const FETCH_LOG_STUDENTS = "FETCH_LOG_STUDENTS";

export const SET_LOADING = "SET_LOADING";
